#--- | Application config
:login: ''               #--- | Your login
:socks_password: ''      #--- | Socks password for md5 authentication
:unix_password: ''       #--- | Unix password for kerberos authentication (default if set)
:state: 'actif'          #--- | Could be, actif, away, idle, lock
:location: '@ Home'      #--- | Set your location
:user_group: 'IONIS'     #--- | Set your IONIS user group
:system: ''              #--- | Set your operating system
